### ISSUE TITLE
Not installable through Google Play for new users (as of 2023.01.31?)

### ISSUE THREAD

**Issue by pipejakob** [astefanich/Shinro#1]
I'd love to be able to try this game, but Google Play won't let new customers install it until it [targets Android API 31](https://support.google.com/googleplay/android-developer/answer/11926878) or above.

If I try to search Google Play for "Shinro," this is filtered out of the search results, and if I navigate to the Google Play link directly, here is the error I get:

![Screenshot_2023-03-10-13-16-31-70_b5a5c5cb02ca09c784c5d88160e2ec24~2](https://user-images.githubusercontent.com/1605981/224430318-df5cdc91-6103-4fc1-a3a4-b735d0b4e5bc.jpg)

I believe rebuilding with the `compileSdkVersion` and `targetSdkVersion`s set to 31 (instead of 29 [here](https://github.com/veyga/Shinro/blob/253d5b2a361c0ecf541477cb5f379320c4ecbb3c/app/build.gradle#L14)) should be enough to fix this, but you may need to upgrade other dependencies as well to accommodate the change.

Cheers!

**Comment by veyga** [comment]
Thx for the heads up. I'll see if I can't upgrade the api version sometime in the next few days.

**Comment by veyga** [comment]
@pipejakob this should be available for you now. Let me know if you are still running into issues. You will need a google games account, if you wish to interact with those features. Best of luck with the game!

**Comment by pipejakob** [comment]
Awesome, that was quick! Thanks for fixing, and for the great game! Everything looks good on my end.
